### ISSUE TITLE
Could you please provide a link of the EBB dataset?

### ISSUE THREAD

**Issue by CaptainEven** [Soester10/Bokeh-Rendering-with-Vision-Transformers#3]
I can not find it in colab now

**Comment by Soester10** [comment]
Hey, You'll need to register for this to access the dataset: https://competitions.codalab.org/competitions/24717

**Comment by CaptainEven** [comment]
> Hey, You'll need to register for this to access the dataset: https://competitions.codalab.org/competitions/24717

I have registered, but can not find any download link

![image](https://github.com/Soester10/Bokeh-Rendering-with-Vision-Transformers/assets/9303747/65390f35-c9b0-46c4-8513-66c0b3e1bb9e)

**Comment by CaptainEven** [comment]
![image](https://github.com/Soester10/Bokeh-Rendering-with-Vision-Transformers/assets/9303747/1aaf5e48-d5ec-4d45-a0bd-64a27bc0460a)

**Comment by Soester10** [comment]
Okay, use this

Training: [https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/Training.zip](https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/Training.zip)

Validation: [https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/ValidationBokehFree.zip](https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/ValidationBokehFree.zip)

Testing: [https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/TestBokehFree.zip](https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/TestBokehFree.zip)

**Comment by CaptainEven** [comment]
> 

Great appreciation for the help! Thanks for the wonderful work and help!

**Comment by xuhangc** [comment]
Hi, the links are expired. Could you share the dataset you download @CaptainEven @Soester10
